
- hosts: all
  vars:
   username: itesciadm
  tasks:
          - name: Add user
            user: 
             name: "{{username}}"
             state: present 
             groups: adm, sudo  
             home: '/home/"{{username}}' 
             shell: '/bin/bash'
             password: '$6$giUmFnsMF/ebie$a39nx0s..NFWsZqBeZKsr3uqCasmrkezZdvTfV7NKLATYG.U9fsZdZTN1wpNZgijM9VFb2bLXCTytNDV5VGyu1' 
             generate_ssh_key: yes 
       
          - name : permission   
            command: pveum useradd "{{username}}"@pam -group Administrateur -password itescia
