
- hosts: all
  
  vars:
      api_user: root@pam 
      api_password: itescia

  tasks:
      - name: comment enterprise package repo
        lineinfile:
          path: "/etc/apt/sources.list.d/pve-enterprise.list"
          regexp: '^deb (.*)$'
          line: '#deb \1'
        tags: test

      - name: "Installation de packages sur les proxmox"
        apt:
            update_cache: yes
            name        : "{{ item }}"
            state       : latest
        with_items: 
            - htop
            - python-pip

      - name: "Deploiement-VM-Proxmox1"
        proxmox_kvm:
            api_user    : "{{api_user}}"
            api_password: "{{api_password}}"
            api_host    : 192.168.247.130
            name        : ansibled1
            node        : proxmox1
            ide         : '{"ide0":"local:iso/ubuntu-18.04.3-live-server-amd64.iso,media=cdrom"}'
            autostart   : yes
            cores       : 1

      - name: "Deploiement-VM-Proxmox2"
        proxmox_kvm:
            api_user    : "{{api_user}}"
            api_password: "{{api_password}}"
            api_host    : 192.168.247.128
            name        : ansibled2
            node        : proxmox2
            ide         : '{"ide0":"local:iso/ubuntu-18.04.3-live-server-amd64.iso,media=cdrom"}'
            autostart   : yes
            cores       : 1

      - name: "Deploiement-VM-Proxmox3"
        proxmox_kvm:
            api_user    : "{{api_user}}"
            api_password: "{{api_password}}"
            api_host    : 192.168.247.131
            name        : ansibled3
            node        : proxmox3
            ide         : '{"ide0":"local:iso/ubuntu-18.04.3-live-server-amd64.iso,media=cdrom"}'
            autostart   : yes
            cores       : 1
